export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCESS = "AUTH_LOGIN_SUCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const ADVERTS_LOADED = "ADVERTS_LOADED";
export const ADVERT_CREATED = "ADVERT_CREATED";

export const UI_RESET_ERROR = "UI_RESET_ERROR";
