export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCESS = "AUTH_LOGIN_SUCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const ADVERTS_LOADED_REQUEST = "ADVERTS_LOADED_REQUEST";
export const ADVERTS_LOADED_SUCESS = "ADVERTS_LOADED_SUCESS";
export const ADVERTS_LOADED_FAILURE = "ADVERTS_LOADED_FAILURE";

export const ADVERT_LOADED_REQUEST = "ADVERT_LOADED_REQUEST";
export const ADVERT_LOADED_SUCESS = "ADVERT_LOADED_SUCESS";
export const ADVERT_LOADED_FAILURE = "ADVERT_LOADED_FAILURE";

export const ADVERT_CREATED_REQUEST = "ADVERT_CREATED_REQUEST";
export const ADVERT_CREATED_SUCESS = "ADVERT_CREATED_SUCESS";
export const ADVERT_CREATED_FAILURE = "ADVERT_CREATED_FAILURE";

export const ADVERT_DELETED_REQUEST = "ADVERT_DELETED_REQUEST";
export const ADVERT_DELETED_SUCESS = "ADVERT_DELETED_SUCESS";
export const ADVERT_DELETED_FAILURE = "ADVERT_DELETED_FAILURE";

export const UI_RESET_ERROR = "UI_RESET_ERROR";
